### ISSUE TITLE
rtx переименовали в mise

### ISSUE THREAD

**Issue by aksilont** [EncodedTeam/MdEditor#5]
# Mise
Как правильно перейти на mise:
https://mise.jdx.dev/rtx.html

 # GitHub Actions
вместо
`- uses: jdx/rtx-action@v1`
использовать
`- uses: jdx/mise-action@v2`

Пример:
```
jobs:
  build:
    name: Build MdEditor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - name: Build
        run: exec ./.github/build.sh
```
